name: Build and test Materialifier

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Use Node.js '16'
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install
    - run: yarn global add rollup
    - run: yarn build
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Use Node.js '16'
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - run: yarn install
    - run: yarn test
    - run: ls
    - uses: codecov/codecov-action@v3.1.0
      with:
        files: ./junit.xml
        flags: unittests
        fail_ci_if_error: true
        verbose: true
